package view;

import javax.swing.JButton;
import java.awt.Insets;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.JLabel;

public class FrameRegistraPresenca extends FrameCadastro
{
    public int codCargo;
    private JLabel lblTurma;
    private JTextField textField;
    private JTextField textField_1;
    private JLabel lblAluno;
    private JLabel lblAluno_1;
    private JLabel lblAluno_2;
    private JRadioButton radioButton;
    private JRadioButton radioButton_1;
    private JRadioButton radioButton_2;
    
    public FrameRegistraPresenca() {
        this.setTitle("Registro de Presença");
        final GridBagLayout gridBagLayout = (GridBagLayout)this.pnlCenter.getLayout();
        gridBagLayout.columnWidths = new int[] { 0, 0, 48, 0, 0 };
        gridBagLayout.rowWeights = new double[] { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 };
        gridBagLayout.columnWeights = new double[] { 0.0, 0.0, 0.0, 0.0, 1.0 };
        this.lblTurma = new JLabel("Turma:");
        final GridBagConstraints gbc_lblTurma = new GridBagConstraints();
        gbc_lblTurma.anchor = 13;
        gbc_lblTurma.insets = new Insets(0, 0, 5, 5);
        gbc_lblTurma.gridx = 1;
        gbc_lblTurma.gridy = 1;
        this.pnlCenter.add(this.lblTurma, gbc_lblTurma);
        this.textField = new JTextField();
        final GridBagConstraints gbc_textField = new GridBagConstraints();
        gbc_textField.fill = 2;
        gbc_textField.insets = new Insets(0, 0, 5, 5);
        gbc_textField.gridx = 2;
        gbc_textField.gridy = 1;
        this.pnlCenter.add(this.textField, gbc_textField);
        this.textField.setColumns(1);
        final JButton btnPesquisar = new JButton("Pesquisar");
        final GridBagConstraints gbc_btnPesquisar = new GridBagConstraints();
        gbc_btnPesquisar.insets = new Insets(0, 0, 5, 5);
        gbc_btnPesquisar.gridx = 3;
        gbc_btnPesquisar.gridy = 1;
        this.pnlCenter.add(btnPesquisar, gbc_btnPesquisar);
        final JLabel lblNome = new JLabel("Data:");
        final GridBagConstraints gbc_lblNome = new GridBagConstraints();
        gbc_lblNome.anchor = 13;
        gbc_lblNome.insets = new Insets(0, 0, 5, 5);
        gbc_lblNome.gridx = 1;
        gbc_lblNome.gridy = 2;
        this.pnlCenter.add(lblNome, gbc_lblNome);
        (this.textField_1 = new JTextField()).setText("25/05/2023");
        final GridBagConstraints gbc_textField_1 = new GridBagConstraints();
        gbc_textField_1.insets = new Insets(0, 0, 5, 5);
        gbc_textField_1.fill = 2;
        gbc_textField_1.gridx = 2;
        gbc_textField_1.gridy = 2;
        this.pnlCenter.add(this.textField_1, gbc_textField_1);
        this.textField_1.setColumns(10);
        this.lblAluno = new JLabel("Aluno 1");
        final GridBagConstraints gbc_lblAluno = new GridBagConstraints();
        gbc_lblAluno.insets = new Insets(0, 0, 5, 5);
        gbc_lblAluno.gridx = 1;
        gbc_lblAluno.gridy = 3;
        this.pnlCenter.add(this.lblAluno, gbc_lblAluno);
        this.radioButton_1 = new JRadioButton("");
        final GridBagConstraints gbc_radioButton_1 = new GridBagConstraints();
        gbc_radioButton_1.insets = new Insets(0, 0, 5, 5);
        gbc_radioButton_1.gridx = 2;
        gbc_radioButton_1.gridy = 3;
        this.pnlCenter.add(this.radioButton_1, gbc_radioButton_1);
        this.lblAluno_1 = new JLabel("Aluno 2");
        final GridBagConstraints gbc_lblAluno_1 = new GridBagConstraints();
        gbc_lblAluno_1.insets = new Insets(0, 0, 5, 5);
        gbc_lblAluno_1.gridx = 1;
        gbc_lblAluno_1.gridy = 4;
        this.pnlCenter.add(this.lblAluno_1, gbc_lblAluno_1);
        (this.radioButton = new JRadioButton("")).setSelected(true);
        final GridBagConstraints gbc_radioButton = new GridBagConstraints();
        gbc_radioButton.insets = new Insets(0, 0, 5, 5);
        gbc_radioButton.gridx = 2;
        gbc_radioButton.gridy = 4;
        this.pnlCenter.add(this.radioButton, gbc_radioButton);
        this.lblAluno_2 = new JLabel("Aluno 3");
        final GridBagConstraints gbc_lblAluno_2 = new GridBagConstraints();
        gbc_lblAluno_2.insets = new Insets(0, 0, 0, 5);
        gbc_lblAluno_2.gridx = 1;
        gbc_lblAluno_2.gridy = 5;
        this.pnlCenter.add(this.lblAluno_2, gbc_lblAluno_2);
        (this.radioButton_2 = new JRadioButton("")).setSelected(true);
        final GridBagConstraints gbc_radioButton_2 = new GridBagConstraints();
        gbc_radioButton_2.insets = new Insets(0, 0, 0, 5);
        gbc_radioButton_2.gridx = 2;
        gbc_radioButton_2.gridy = 5;
        this.pnlCenter.add(this.radioButton_2, gbc_radioButton_2);
    }
}